---
gitian_user: vagrant
download_directory: /tmp/gitian
vm_builder_name: 'vm-builder-0.12.4+bzr494'
vm_builder_url: 'http://archive.ubuntu.com/ubuntu/pool/universe/v/vm-builder/vm-builder_0.12.4+bzr494.orig.tar.gz'
gitian_builder_url: https://github.com/devrandom/gitian-builder
koto_git_repo_url: https://github.com/KotoDevelopers/koto
koto_gitian_sigs_repo: https://github.com/KotoDevelopers/gitian.sigs
koto_version: master
gitian_host_ip: 10.0.2.15
lxc_guest_ip: 10.0.3.5
koto_developer_pubkeys:
  - name: wo
    id: 8BCABC42AC606C7311775A63FD04BBFAD00AFDDE
