---
- name: Apply the Koto Gitian builder role.
  become: yes
  hosts: localhost:koto-build
  gather_facts: False
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  vars:
    koto_git_repo_url: https://github.com/KotoDevelopers/koto
    koto_version: develop
    gpg_key_name: ''
    git_name: ''
    git_email: ''
    gpg_key_id: '' # optional
    ssh_key_name: '' # optional
  roles:
    - role: common
      tags: common
    - role: gitian
      tags: gitian
