---
- name: Apply the Koto Gitian builder role.
  become: yes
  hosts: localhost:koto-build
  vars:
    koto_git_repo_url: https://github.com/KotoDevelopers/koto
    koto_version: v2.0.0
    gpg_key_name: ''
    git_name: ''
    git_email: ''
    gpg_key_id: '' # optional
    ssh_key_name: '' # optional
  roles:
    - role: common
      tags: common
    - role: gitian
      tags: gitian
